# Window defaults
WIN_WIDTH = 1440
WIN_HEIGHT = 900
FIELD_WIDTH = 990
FIELD_HEIGHT = 860
WIN_DARK_COLOR = '#303030'
WIN_BRIGHT_COLOR = 'white'
FIELD_DARK_COLOR = '#202020'
FIELD_BRIGHT_COLOR = 'gray'
WIN_TITLE = "PyQt5 Graph Vizualizer"

# Vertex defaults
VERTEX_COLOR = 'salmon'
VERTEX_SIZE = 50
OFFSET = VERTEX_SIZE / 2

# Verge defaults
VERGE_COLOR = 'white'
VERGE_WIDTH = 6

# Mouse codes
MOUSE_LEFT = 1
MOUSE_RIGHT = 2
MOUSE_MIDDLE = 3

# Operations
ADD_VERTEX = 1
DELETE_VERTEX = 2
MOVE_VERTEX = 3
ADD_VERGE = 4
DELETE_VERGE = 5
