# Window defaults
WIN_WIDTH = 1280
WIN_HEIGHT = 800
FIELD_SIZE = 800
FIELD_COLOR = '#151515'
WIN_TITLE = "PyQt5 Graph Vizualizer"

# Vertex defaults
VERTEX_COLOR = 'salmon'
VERTEX_RADIUS = 40

# Verge defaults
VERGE_COLOR = 'white'
VERGE_WIDTH = 6

# Mouse codes
MOUSE_LEFT = 1
MOUSE_RIGHT = 2
MOUSE_MIDDLE = 3

# Operations
ADD_VERTEX = 1
DELETE_VERTEX = 2
MOVE_VERTEX = 3
ADD_VERGE = 4
DELETE_VERGE = 5
