# Window defaults
WIN_WIDTH = 1800
WIN_HEIGHT = 1000
FIELD_WIDTH = 1350
FIELD_HEIGHT = 950
TABLE_WIDTH = 400
TABLE_HEIGHT = 300

WIN_DARK_COLOR = '#303030'
WIN_BRIGHT_COLOR = 'white'
FIELD_DARK_COLOR = '#151515'
FIELD_BRIGHT_COLOR = 'gray'
WIN_TITLE = "Graph Visualizer"

DIALOG_WIDTH = 300
DIALOG_HEIGHT = 200

CACHE_SIZE = 10

# Vertex defaults
VERTEX_COLOR = 'salmon'
VERTEX_SIZE = 50
OFFSET = VERTEX_SIZE / 2

# Verge defaults
VERGE_COLOR = 'white'
VERGE_WIDTH = 5
ARROW_SIZE = 8

# Mouse codes
MOUSE_LEFT = 1
MOUSE_RIGHT = 2
MOUSE_MIDDLE = 3

# Operations
ADD_VERTEX = 1
DELETE_VERTEX = 2
MOVE_VERTEX = 3
ADD_VERGE = 4
DELETE_VERGE = 5
